swagger: "2.0"
info:
    title: Count Up
    description: A production-ready Go service deployed on Kubernetes
    version: 1.0.0
host: localhost:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /:
        get:
            tags:
                - web
            summary: Index web
            operationId: web#Index
            produces:
                - text/html
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: byte
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/WebIndexUnauthorizedResponseBody'
            schemes:
                - http
    /another:
        get:
            tags:
                - web
            summary: Another web
            operationId: web#Another
            produces:
                - text/html
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                        format: byte
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/WebAnotherUnauthorizedResponseBody'
            schemes:
                - http
    /api/v1/auth/token:
        post:
            tags:
                - api
            summary: AuthToken api
            operationId: api#AuthToken
            parameters:
                - name: AuthTokenRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/APIAuthTokenRequestBody'
                    required:
                        - provider
                        - access_token
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/APIAuthTokenResponseBody'
                        required:
                            - token
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/APIAuthTokenUnauthorizedResponseBody'
                "429":
                    description: Too Many Requests response.
                    schema:
                        $ref: '#/definitions/APIAuthTokenExistingIncrementRequestResponseBody'
            schemes:
                - http
    /api/v1/counter:
        get:
            tags:
                - api
            summary: CounterGet api
            description: |4-
                **Required security scopes for jwt**:
                  * `api`
            operationId: api#CounterGet
            parameters:
                - name: Authorization
                  in: header
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/CounterInfo'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/APICounterGetUnauthorizedResponseBody'
                "429":
                    description: Too Many Requests response.
                    schema:
                        $ref: '#/definitions/APICounterGetExistingIncrementRequestResponseBody'
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
        post:
            tags:
                - api
            summary: CounterIncrement api
            description: |4-
                **Required security scopes for jwt**:
                  * `api`
            operationId: api#CounterIncrement
            parameters:
                - name: Authorization
                  in: header
                  required: true
                  type: string
                - name: CounterIncrementRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/APICounterIncrementRequestBody'
                    required:
                        - user
            responses:
                "202":
                    description: Accepted response.
                    schema:
                        $ref: '#/definitions/CounterInfo'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/APICounterIncrementUnauthorizedResponseBody'
                "429":
                    description: Too Many Requests response.
                    schema:
                        $ref: '#/definitions/APICounterIncrementExistingIncrementRequestResponseBody'
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /api/v1/openapi.json:
        get:
            tags:
                - api
            summary: Download gen/http/openapi3.json
            operationId: api#/api/v1/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /echo:
        post:
            tags:
                - teapot
            summary: Echo teapot
            operationId: teapot#Echo
            parameters:
                - name: EchoRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TeapotEchoRequestBody'
                    required:
                        - text
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TeapotEchoResponseBody'
                        required:
                            - text
            schemes:
                - http
    /login/google:
        get:
            tags:
                - web
            summary: LoginGoogle web
            operationId: web#LoginGoogle
            responses:
                "302":
                    description: Found response.
                    headers:
                        Location:
                            type: string
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/WebLoginGoogleUnauthorizedResponseBody'
            schemes:
                - http
    /login/google/callback:
        get:
            tags:
                - web
            summary: LoginGoogleCallback web
            operationId: web#LoginGoogleCallback
            parameters:
                - name: code
                  in: query
                  required: true
                  type: string
                - name: state
                  in: query
                  required: true
                  type: string
            responses:
                "302":
                    description: Found response.
                    headers:
                        Location:
                            type: string
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/WebLoginGoogleCallbackUnauthorizedResponseBody'
            schemes:
                - http
    /logout:
        get:
            tags:
                - web
            summary: Logout web
            operationId: web#Logout
            responses:
                "302":
                    description: Found response.
                    headers:
                        Location:
                            type: string
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/WebLogoutUnauthorizedResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - teapot
            summary: Download gen/http/openapi3.json
            operationId: teapot#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /session/token:
        get:
            tags:
                - web
            summary: SessionToken web
            operationId: web#SessionToken
            produces:
                - application/json
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/WebSessionTokenResponseBody'
                        required:
                            - token
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/WebSessionTokenUnauthorizedResponseBody'
            schemes:
                - http
    /static/*:
        get:
            tags:
                - web
            summary: Download static/
            operationId: web#/static/*
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    APIAuthTokenExistingIncrementRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: AuthToken_existing_increment_request_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APIAuthTokenRequestBody:
        title: APIAuthTokenRequestBody
        type: object
        properties:
            access_token:
                type: string
                example: Aut culpa quo sit dolor aperiam consequatur.
            provider:
                type: string
                example: google
                enum:
                    - google
        example:
            access_token: Harum iusto quas.
            provider: google
        required:
            - provider
            - access_token
    APIAuthTokenResponseBody:
        title: APIAuthTokenResponseBody
        type: object
        properties:
            token:
                type: string
                example: Illo vel qui ipsa adipisci.
        example:
            token: Quam eaque ipsa eius quaerat.
        required:
            - token
    APIAuthTokenUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: AuthToken_unauthorized_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APICounterGetExistingIncrementRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CounterGet_existing_increment_request_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APICounterGetUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CounterGet_unauthorized_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APICounterIncrementExistingIncrementRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CounterIncrement_existing_increment_request_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    APICounterIncrementRequestBody:
        title: APICounterIncrementRequestBody
        type: object
        properties:
            user:
                type: string
                example: Voluptas quae perspiciatis illo suscipit.
        example:
            user: Nesciunt vero repudiandae.
        required:
            - user
    APICounterIncrementUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CounterIncrement_unauthorized_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    CounterInfo:
        title: 'Mediatype identifier: application/vnd.countup.counter-info`; view=default'
        type: object
        properties:
            count:
                type: integer
                example: 718974130
                format: int32
            last_increment_at:
                type: string
                example: Consequuntur cupiditate pariatur aut placeat.
            last_increment_by:
                type: string
                example: Ipsam nesciunt minima cupiditate.
            next_finalize_at:
                type: string
                example: Amet voluptas ex nostrum aperiam explicabo sed.
        description: CounterGetResponseBody result type (default view)
        example:
            count: 837784502
            last_increment_at: Eius rerum.
            last_increment_by: Sint asperiores sed voluptas voluptatem.
            next_finalize_at: Accusamus maiores ut voluptas.
        required:
            - count
            - last_increment_by
            - last_increment_at
            - next_finalize_at
    TeapotEchoRequestBody:
        title: TeapotEchoRequestBody
        type: object
        properties:
            text:
                type: string
                example: Adipisci saepe et vel magnam dolor.
        example:
            text: At officia repudiandae ex ipsam labore.
        required:
            - text
    TeapotEchoResponseBody:
        title: TeapotEchoResponseBody
        type: object
        properties:
            text:
                type: string
                example: Id accusamus quam aut.
        example:
            text: Voluptatem ipsam et dolorem quos nihil assumenda.
        required:
            - text
    WebAnotherUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Another_unauthorized_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    WebIndexUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Index_unauthorized_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    WebLoginGoogleCallbackUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: LoginGoogleCallback_unauthorized_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    WebLoginGoogleUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: LoginGoogle_unauthorized_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    WebLogoutUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Logout_unauthorized_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    WebSessionTokenResponseBody:
        title: WebSessionTokenResponseBody
        type: object
        properties:
            token:
                type: string
                example: Qui quaerat nobis incidunt porro quam quam.
        example:
            token: Nobis reiciendis voluptate totam ex eos.
        required:
            - token
    WebSessionTokenUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: SessionToken_unauthorized_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: |4-
            **Security Scopes**:
              * `api`: no description
        name: Authorization
        in: header
